apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-mysql-config
  namespace: default
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      - job_name: "mysql-logs"
        static_configs:
          - targets:
              - localhost
            labels:
              job: "mysql"
              __path__: "/var/lib/mysql/mysql-0.log"