apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-secrets
  namespace: default
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "1b0de5f0-fb09-41c0-a695-d92b5a5f7bed"
    keyvaultName: yg-aks-keyvault
    objects: |
      array:
        - |
          objectName: mysql-password
          objectType: secret
    tenantId: "a7da4436-e498-4245-8b58-1e0554afa193"
