apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ingress-nginx
data:
  nginx.conf: |
    pid /tmp/nginx/nginx.pid;
    daemon off;
    worker_processes 1;
    worker_rlimit_nofile 1047552;
    worker_shutdown_timeout 240s;

    events {
        multi_accept on;
        worker_connections 16384;
        use epoll;
    }

    http {
        lua_package_path "/etc/nginx/lua/?.lua;;";
        lua_shared_dict balancer_ewma 10M;
        lua_shared_dict certificate_data 20M;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate     /mnt/secrets-store/yg-cert.crt;
        ssl_certificate_key /mnt/secrets-store/yg-cert.key;
        
        upstream upstream_balancer {
            server 0.0.0.1;
            balancer_by_lua_file /etc/nginx/lua/nginx/ngx_conf_balancer.lua;
        }

        server {
            listen 80 default_server;
            listen [::]:80 default_server;
            listen 443 ssl default_server;
            listen [::]:443 ssl default_server;

            server_name _;

            ssl_certificate_by_lua_file /etc/nginx/lua/nginx/ngx_conf_certificate.lua;

            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_pass http://upstream_balancer;
                proxy_redirect off;
            }
        }

        server {
            listen 443 ssl;
            listen [::]:443 ssl;
            server_name yg.woongjin.com;

            ssl_certificate_by_lua_file /etc/nginx/lua/nginx/ngx_conf_certificate.lua;

            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_pass http://upstream_balancer;
                proxy_redirect off;
            }
        }
    }
